-- +goose Up

CREATE TABLE "Users" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IsOrganization" bool NOT NULL,
  "Name" varchar NOT NULL,
  "Email" varchar UNIQUE NOT NULL,
  "About" varchar,
  "AvatarURL" varchar,
  "Images" varchar,
  "AuthProvider" varchar,
  "AuthHash" varchar,
  "RegisteredAt" timestamptz NOT NULL,
  "LastVisitedAt" timestamptz NOT NULL,
  "IsOnline" bool NOT NULL,
  "LocationLat" float,
  "LocationLong" float
);

CREATE TABLE "Donations" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CreatedById" int NOT NULL,
  "CreatedAt" timestamptz NOT NULL,
  "StartsAt" timestamptz,
  "EndsAt" timestamptz,
  "Description" varchar NOT NULL,
  "Images" varchar,
  "ServingsTotal" int,
  "ServingsLeft" int,
  "LocationLat" float NOT NULL,
  "LocationLong" float NOT NULL
);

CREATE TABLE "DonationRequests" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DonationId" int,
  "RequesterId" int,
  "Comment" varchar,
  "Images" varchar,
  "CreatedAt" timestamptz,
  "AcceptedAt" timestamptz,
  "AcceptedById" int,
  "ConfirmedAt" timestamptz,
  "ConfirmedById" int
);

CREATE TABLE "DonationEvents" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DonationId" int NOT NULL,
  "CreatedBy" int NOT NULL,
  "CreatedAt" timestamptz NOT NULL,
  "Comment" varchar NOT NULL,
  "Images" varchar,
  "ReplyToId" int
);

CREATE TABLE "Ratings" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CreatedAt" timestamptz NOT NULL,
  "FromId" int NOT NULL,
  "ToId" int NOT NULL,
  "Rating" int NOT NULL,
  "Comment" varchar,
  "Images" varchar,
  "LocationLat" float NOT NULL,
  "LocationLong" float NOT NULL
);

CREATE TABLE "Notifications" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CreatedAt" timestamptz NOT NULL,
  "DonationId" int,
  "DonationEventId" int,
  "DonationRequestId" int,
  "RatingId" int,
  "UserId" int,
  "Comment" varchar
);

CREATE TABLE "NotificationHistory" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NotificationId" int NOT NULL,
  "UserId" int NOT NULL,
  "SentAt" timestamptz NOT NULL,
  "ReadAt" timestamptz
);

ALTER TABLE "Donations" ADD FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id");

ALTER TABLE "DonationRequests" ADD FOREIGN KEY ("DonationId") REFERENCES "Donations" ("Id");

ALTER TABLE "DonationRequests" ADD FOREIGN KEY ("RequesterId") REFERENCES "Users" ("Id");

ALTER TABLE "DonationRequests" ADD FOREIGN KEY ("AcceptedById") REFERENCES "Users" ("Id");

ALTER TABLE "DonationRequests" ADD FOREIGN KEY ("ConfirmedById") REFERENCES "Users" ("Id");

ALTER TABLE "DonationEvents" ADD FOREIGN KEY ("DonationId") REFERENCES "Donations" ("Id");

ALTER TABLE "DonationEvents" ADD FOREIGN KEY ("CreatedBy") REFERENCES "Users" ("Id");

ALTER TABLE "DonationEvents" ADD FOREIGN KEY ("ReplyToId") REFERENCES "DonationEvents" ("Id");

ALTER TABLE "Ratings" ADD FOREIGN KEY ("FromId") REFERENCES "Users" ("Id");

ALTER TABLE "Ratings" ADD FOREIGN KEY ("ToId") REFERENCES "Users" ("Id");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("DonationId") REFERENCES "Donations" ("Id");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("DonationEventId") REFERENCES "DonationEvents" ("Id");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("DonationRequestId") REFERENCES "DonationRequests" ("Id");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("RatingId") REFERENCES "Ratings" ("Id");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("UserId") REFERENCES "DonationRequests" ("Id");

ALTER TABLE "NotificationHistory" ADD FOREIGN KEY ("NotificationId") REFERENCES "Notifications" ("Id");

ALTER TABLE "NotificationHistory" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("Id");

-- +goose Down
drop table NotificationHistory;
drop table Notifications;
drop table DonationRequests;
drop table DonationEvents;
drop table Donations;
drop table Ratings;
drop table Users;
